### ISSUE TITLE
Fazer o pré processamento dos dados

### ISSUE THREAD

**Issue by dougAlvs** [fga-eps-mds/2022-2-IsItKbs#17]
## Descrição
Fazer todo o trabalho de processamento de dados, desde pegar a base de dados intocada até fazer o processo de feature extraction e deixá-la pronta para ser usada pelos algoritmos de machine learning

## Tarefas
- [x] Limpar a base de dados.
- [x] Fazer o feature extraction.

## Critérios de Aceitação
- [x] Bases de dados prontas para o treinamento.

**Comment by dougAlvs** [comment]
Hey @arthurmlv I’m using Zenhub in GitHub, [click this link](https://app.zenhub.com/workspaces/fga-eps-mds2022-2-squad03-635baffe1f35febac4db0c58/board) to join my workspace and see other features available in GitHub or [download the Zenhub extension](https://www.zenhub.com/extension) and sign up with your GitHub account.
  _Posted using [Zenhub](https://www.zenhub.com)_

**Comment by G16C** [comment]
Creio que podemos fechar essa issue, não?

**Comment by G16C** [comment]
Como todas as issues relacionadas foram completadas, e os critérios foram atingidos, essa sprint está finalizada.
