### ISSUE TITLE
Avaliar e entregar os modelos

### ISSUE THREAD

**Issue by dougAlvs** [fga-eps-mds/2022-2-IsItKbs#19]
## Descrição
Fazer a avaliação do modelo treinado e, caso necessário, refazer o processo de treinamento para melhorar os resultados obtidos.

## Tarefas
- [x] Avaliar a eficácia do modelo.
- [x] Se necessário, refazer o treinamento.

## Critérios de aceitação
- [x] Acurácia aceitável na identificação de keyboard smashing.

**Comment by G16C** [comment]
Função protótipo está pronta, falta empacotar

**Comment by dougAlvs** [comment]
A função foi finalizada, testada e empacotada.
