### ISSUE TITLE
Documentação em acordo com a comunidade

### ISSUE THREAD

**Issue by dougAlvs** [fga-eps-mds/2022-2-IsItKbs#47]
## Descrição
Fazer a adição dos documentos que faltam para o projeto estar dentro dos padrões estabelecidos pela comunidade.

## Tarefas
- [x] Elaborar o código de conduta.
- [x] Elaborar o guia de contribuição.
- [x] Elaborar a security policy.
- [x] Elaborar o template de issues.
- [x] Elaborar o template de pull requests.

## Critério de aceitação
- [x] Todas as tarefas acima estarem completas.

**Comment by dougAlvs** [comment]
Como todos os documentos padrões da comunidade restantes foram adicionados essa issue está completa.
