### ISSUE TITLE
Organização da Equipe

### ISSUE THREAD

**Issue by dougAlvs** [fga-eps-mds/2022-2-IsItKbs#85]
## Descrição
Épico para a familiarização inicial da equipe com os métodos ágeis e organização para que o trabalho em grupo flua de maneira adequada.

## Tarefas
- [x] Criação de canais de comunicação.
- [x] Estudo do método scrum

## Critérios de aceitação
- [x] Processo inicial de familiarização ok.
